
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jul 09 14:30:46 CEST 2025
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int FUNCTION = 8;
  public static final int CONST = 4;
  public static final int EQUALS = 32;
  public static final int INTEGER = 11;
  public static final int LPAREN = 33;
  public static final int REPEAT = 16;
  public static final int INT = 24;
  public static final int MINUS = 27;
  public static final int WRITE = 23;
  public static final int STAR = 28;
  public static final int RPAREN = 34;
  public static final int SEMICOLON = 40;
  public static final int TYPE = 20;
  public static final int IN = 10;
  public static final int OR = 13;
  public static final int COMMA = 37;
  public static final int DOTDOT = 38;
  public static final int BEGIN = 2;
  public static final int UNTIL = 21;
  public static final int PLUS = 26;
  public static final int ASSIGN = 31;
  public static final int IF = 9;
  public static final int ID = 42;
  public static final int DOT = 39;
  public static final int OF = 12;
  public static final int EOF = 0;
  public static final int BOOLEAN = 3;
  public static final int TRUE = 19;
  public static final int error = 1;
  public static final int PROGRAM = 15;
  public static final int LBRACK = 35;
  public static final int COLON = 41;
  public static final int ELSE = 5;
  public static final int RBRACK = 36;
  public static final int THEN = 18;
  public static final int NE = 30;
  public static final int END = 6;
  public static final int STRING = 25;
  public static final int FALSE = 7;
  public static final int GT = 29;
  public static final int VAR = 22;
  public static final int PROCEDURE = 14;
  public static final int SET = 17;
}

